name: Build VRigUnity

on:
  workflow_call:
    inputs:
      tag:
        type: string
        default: v0.10.1-macos11
      ref:
        type: string

jobs:
  build:
    name: Build for ${{ matrix.data.systemName }}
    runs-on: ${{ matrix.data.os }}
    strategy:
      fail-fast: false
      matrix:
        data:
          - { targetPlatform: "StandaloneWindows64", systemName: "Windows", os: "ubuntu-latest" }
          - { targetPlatform: "StandaloneLinux64", systemName: "Linux", os: "ubuntu-latest" }
          - { targetPlatform: "StandaloneOSX", systemName: "OSX", os: "ubuntu-latest" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Download libs
        run: bash download_libs.sh "${{ inputs.tag }}"

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.data.targetPlatform }}
          restore-keys: |
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        if: ${{ matrix.data.targetPlatform == 'StandaloneLinux64' }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.data.systemName }} results
          testMode: PlayMode

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.data.targetPlatform == 'StandaloneLinux64' }}
        with:
          name: Results ${{ matrix.data.systemName }}
          path: artifacts

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildName: VRigUnity
          versioning: None
          targetPlatform: ${{ matrix.data.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: VRigUnity-${{ matrix.data.systemName }}
          path: build/${{ matrix.data.targetPlatform }}
