name: Manually Build VRigUnity

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: v0.10.1-macos11
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ inputs.tag }}
      ref: ${{ github.event.ref }}
    secrets: inherit
